// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: proto/coefficient.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateCoefficientRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MarketId       uint32                 `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	NewCoefficient float64                `protobuf:"fixed64,2,opt,name=new_coefficient,json=newCoefficient,proto3" json:"new_coefficient,omitempty"`
	UserId         uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCoefficientRequest) Reset() {
	*x = UpdateCoefficientRequest{}
	mi := &file_proto_coefficient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCoefficientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCoefficientRequest) ProtoMessage() {}

func (x *UpdateCoefficientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coefficient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCoefficientRequest.ProtoReflect.Descriptor instead.
func (*UpdateCoefficientRequest) Descriptor() ([]byte, []int) {
	return file_proto_coefficient_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateCoefficientRequest) GetMarketId() uint32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *UpdateCoefficientRequest) GetNewCoefficient() float64 {
	if x != nil {
		return x.NewCoefficient
	}
	return 0
}

func (x *UpdateCoefficientRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateCoefficientResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MarketId       uint32                 `protobuf:"varint,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	OldCoefficient float64                `protobuf:"fixed64,4,opt,name=old_coefficient,json=oldCoefficient,proto3" json:"old_coefficient,omitempty"`
	NewCoefficient float64                `protobuf:"fixed64,5,opt,name=new_coefficient,json=newCoefficient,proto3" json:"new_coefficient,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCoefficientResponse) Reset() {
	*x = UpdateCoefficientResponse{}
	mi := &file_proto_coefficient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCoefficientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCoefficientResponse) ProtoMessage() {}

func (x *UpdateCoefficientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coefficient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCoefficientResponse.ProtoReflect.Descriptor instead.
func (*UpdateCoefficientResponse) Descriptor() ([]byte, []int) {
	return file_proto_coefficient_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCoefficientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateCoefficientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateCoefficientResponse) GetMarketId() uint32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *UpdateCoefficientResponse) GetOldCoefficient() float64 {
	if x != nil {
		return x.OldCoefficient
	}
	return 0
}

func (x *UpdateCoefficientResponse) GetNewCoefficient() float64 {
	if x != nil {
		return x.NewCoefficient
	}
	return 0
}

func (x *UpdateCoefficientResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetMarketCoefficientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      uint32                 `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketCoefficientRequest) Reset() {
	*x = GetMarketCoefficientRequest{}
	mi := &file_proto_coefficient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketCoefficientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketCoefficientRequest) ProtoMessage() {}

func (x *GetMarketCoefficientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coefficient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketCoefficientRequest.ProtoReflect.Descriptor instead.
func (*GetMarketCoefficientRequest) Descriptor() ([]byte, []int) {
	return file_proto_coefficient_proto_rawDescGZIP(), []int{2}
}

func (x *GetMarketCoefficientRequest) GetMarketId() uint32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

type GetMarketCoefficientResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MarketId            uint32                 `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	CurrentCoefficient  float64                `protobuf:"fixed64,2,opt,name=current_coefficient,json=currentCoefficient,proto3" json:"current_coefficient,omitempty"`
	PreviousCoefficient float64                `protobuf:"fixed64,3,opt,name=previous_coefficient,json=previousCoefficient,proto3" json:"previous_coefficient,omitempty"`
	LastUpdated         int64                  `protobuf:"varint,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Active              bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMarketCoefficientResponse) Reset() {
	*x = GetMarketCoefficientResponse{}
	mi := &file_proto_coefficient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketCoefficientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketCoefficientResponse) ProtoMessage() {}

func (x *GetMarketCoefficientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coefficient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketCoefficientResponse.ProtoReflect.Descriptor instead.
func (*GetMarketCoefficientResponse) Descriptor() ([]byte, []int) {
	return file_proto_coefficient_proto_rawDescGZIP(), []int{3}
}

func (x *GetMarketCoefficientResponse) GetMarketId() uint32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *GetMarketCoefficientResponse) GetCurrentCoefficient() float64 {
	if x != nil {
		return x.CurrentCoefficient
	}
	return 0
}

func (x *GetMarketCoefficientResponse) GetPreviousCoefficient() float64 {
	if x != nil {
		return x.PreviousCoefficient
	}
	return 0
}

func (x *GetMarketCoefficientResponse) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *GetMarketCoefficientResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type StreamCoefficientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventIds      []uint32               `protobuf:"varint,1,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	MarketIds     []uint32               `protobuf:"varint,2,rep,packed,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCoefficientRequest) Reset() {
	*x = StreamCoefficientRequest{}
	mi := &file_proto_coefficient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCoefficientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCoefficientRequest) ProtoMessage() {}

func (x *StreamCoefficientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coefficient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCoefficientRequest.ProtoReflect.Descriptor instead.
func (*StreamCoefficientRequest) Descriptor() ([]byte, []int) {
	return file_proto_coefficient_proto_rawDescGZIP(), []int{4}
}

func (x *StreamCoefficientRequest) GetEventIds() []uint32 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *StreamCoefficientRequest) GetMarketIds() []uint32 {
	if x != nil {
		return x.MarketIds
	}
	return nil
}

type CoefficientUpdateEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	MarketId       uint32                 `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	EventId        uint32                 `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OldCoefficient float64                `protobuf:"fixed64,4,opt,name=old_coefficient,json=oldCoefficient,proto3" json:"old_coefficient,omitempty"`
	NewCoefficient float64                `protobuf:"fixed64,5,opt,name=new_coefficient,json=newCoefficient,proto3" json:"new_coefficient,omitempty"`
	Timestamp      int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CoefficientUpdateEvent) Reset() {
	*x = CoefficientUpdateEvent{}
	mi := &file_proto_coefficient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoefficientUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoefficientUpdateEvent) ProtoMessage() {}

func (x *CoefficientUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coefficient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoefficientUpdateEvent.ProtoReflect.Descriptor instead.
func (*CoefficientUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_coefficient_proto_rawDescGZIP(), []int{5}
}

func (x *CoefficientUpdateEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CoefficientUpdateEvent) GetMarketId() uint32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *CoefficientUpdateEvent) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CoefficientUpdateEvent) GetOldCoefficient() float64 {
	if x != nil {
		return x.OldCoefficient
	}
	return 0
}

func (x *CoefficientUpdateEvent) GetNewCoefficient() float64 {
	if x != nil {
		return x.NewCoefficient
	}
	return 0
}

func (x *CoefficientUpdateEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_coefficient_proto protoreflect.FileDescriptor

const file_proto_coefficient_proto_rawDesc = "" +
	"\n" +
	"\x17proto/coefficient.proto\x12\vcoefficient\"y\n" +
	"\x18UpdateCoefficientRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\rR\bmarketId\x12'\n" +
	"\x0fnew_coefficient\x18\x02 \x01(\x01R\x0enewCoefficient\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"\xdd\x01\n" +
	"\x19UpdateCoefficientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\rR\bmarketId\x12'\n" +
	"\x0fold_coefficient\x18\x04 \x01(\x01R\x0eoldCoefficient\x12'\n" +
	"\x0fnew_coefficient\x18\x05 \x01(\x01R\x0enewCoefficient\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\":\n" +
	"\x1bGetMarketCoefficientRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\rR\bmarketId\"\xda\x01\n" +
	"\x1cGetMarketCoefficientResponse\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\rR\bmarketId\x12/\n" +
	"\x13current_coefficient\x18\x02 \x01(\x01R\x12currentCoefficient\x121\n" +
	"\x14previous_coefficient\x18\x03 \x01(\x01R\x13previousCoefficient\x12!\n" +
	"\flast_updated\x18\x04 \x01(\x03R\vlastUpdated\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"V\n" +
	"\x18StreamCoefficientRequest\x12\x1b\n" +
	"\tevent_ids\x18\x01 \x03(\rR\beventIds\x12\x1d\n" +
	"\n" +
	"market_ids\x18\x02 \x03(\rR\tmarketIds\"\xd4\x01\n" +
	"\x16CoefficientUpdateEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\rR\bmarketId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\rR\aeventId\x12'\n" +
	"\x0fold_coefficient\x18\x04 \x01(\x01R\x0eoldCoefficient\x12'\n" +
	"\x0fnew_coefficient\x18\x05 \x01(\x01R\x0enewCoefficient\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp2\xcf\x02\n" +
	"\x12CoefficientService\x12b\n" +
	"\x11UpdateCoefficient\x12%.coefficient.UpdateCoefficientRequest\x1a&.coefficient.UpdateCoefficientResponse\x12k\n" +
	"\x14GetMarketCoefficient\x12(.coefficient.GetMarketCoefficientRequest\x1a).coefficient.GetMarketCoefficientResponse\x12h\n" +
	"\x18StreamCoefficientUpdates\x12%.coefficient.StreamCoefficientRequest\x1a#.coefficient.CoefficientUpdateEvent0\x01B%Z#github.com/VaheMuradyan/Sport/protob\x06proto3"

var (
	file_proto_coefficient_proto_rawDescOnce sync.Once
	file_proto_coefficient_proto_rawDescData []byte
)

func file_proto_coefficient_proto_rawDescGZIP() []byte {
	file_proto_coefficient_proto_rawDescOnce.Do(func() {
		file_proto_coefficient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coefficient_proto_rawDesc), len(file_proto_coefficient_proto_rawDesc)))
	})
	return file_proto_coefficient_proto_rawDescData
}

var file_proto_coefficient_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_coefficient_proto_goTypes = []any{
	(*UpdateCoefficientRequest)(nil),     // 0: coefficient.UpdateCoefficientRequest
	(*UpdateCoefficientResponse)(nil),    // 1: coefficient.UpdateCoefficientResponse
	(*GetMarketCoefficientRequest)(nil),  // 2: coefficient.GetMarketCoefficientRequest
	(*GetMarketCoefficientResponse)(nil), // 3: coefficient.GetMarketCoefficientResponse
	(*StreamCoefficientRequest)(nil),     // 4: coefficient.StreamCoefficientRequest
	(*CoefficientUpdateEvent)(nil),       // 5: coefficient.CoefficientUpdateEvent
}
var file_proto_coefficient_proto_depIdxs = []int32{
	0, // 0: coefficient.CoefficientService.UpdateCoefficient:input_type -> coefficient.UpdateCoefficientRequest
	2, // 1: coefficient.CoefficientService.GetMarketCoefficient:input_type -> coefficient.GetMarketCoefficientRequest
	4, // 2: coefficient.CoefficientService.StreamCoefficientUpdates:input_type -> coefficient.StreamCoefficientRequest
	1, // 3: coefficient.CoefficientService.UpdateCoefficient:output_type -> coefficient.UpdateCoefficientResponse
	3, // 4: coefficient.CoefficientService.GetMarketCoefficient:output_type -> coefficient.GetMarketCoefficientResponse
	5, // 5: coefficient.CoefficientService.StreamCoefficientUpdates:output_type -> coefficient.CoefficientUpdateEvent
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coefficient_proto_init() }
func file_proto_coefficient_proto_init() {
	if File_proto_coefficient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coefficient_proto_rawDesc), len(file_proto_coefficient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coefficient_proto_goTypes,
		DependencyIndexes: file_proto_coefficient_proto_depIdxs,
		MessageInfos:      file_proto_coefficient_proto_msgTypes,
	}.Build()
	File_proto_coefficient_proto = out.File
	file_proto_coefficient_proto_goTypes = nil
	file_proto_coefficient_proto_depIdxs = nil
}
